version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://ubuntu:fasil1090@db:5432/open_flights_test
      # Add other environment variables as needed
    volumes:
      - .:/app

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ubuntu
      POSTGRES_PASSWORD: fasil1090
      POSTGRES_DB: open_flights_test
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: {}


